# Generated by Django 3.0.5 on 2020-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingdb',
            name='image',
            field=models.ImageField(default=1, upload_to='none'),
            preserve_default=False,
        ),
    ]
