# Generated by Django 3.0.7 on 2020-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200706_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingdb',
            name='image',
            field=models.FileField(upload_to='portfolio/static/images/uploaded/'),
        ),
    ]
