# Generated by Django 3.0.7 on 2020-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200707_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingdb',
            name='series',
            field=models.CharField(choices=[('None', 'None'), ('Test', 'Test'), ('Test 2', 'Test 2')], default=1, max_length=100),
        ),
    ]
