# Generated by Django 3.0.7 on 2020-07-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200727_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='bio',
            field=models.TextField(default='filler'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.series'),
        ),
    ]
